Use a secret for db credentials
plone/helm-charts pull request #9
Opened 2024-04-25 13:37 UTC by tschorr

Fix #8.

2024-04-25 18:43 UTC, xiru approved these changes

2024-04-25 20:53 UTC, stevepiercy requested changes
Same three suggestions across the 4 README.mds.

2024-04-25 20:53 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +Database credentials (database name, user name, password) are expected in a secret.
Is host required as well, or is localhost assumed as default?

```suggestion
Database credentials (database name, user name, and password) are expected in a secret.
```

2024-04-25 20:53 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +
```suggestion

See also the Kubernetes documentation [Create a Secret](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#create-a-secret).

```

2024-04-25 20:53 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +[Create the secret](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#create-a-secret) e.g. using `kubectl`:
```suggestion
Using the `kubectl` command, you can create a secret.
```

2024-04-25 20:53 UTC, stevepiercy commented on plone6-classic-pg/README.md
> +Database credentials (database name, user name, password) are expected in a secret.
Is host required as well, or is localhost assumed as default?

```suggestion
Database credentials (database name, user name, and password) are expected in a secret.
```

2024-04-25 20:53 UTC, stevepiercy commented on plone6-classic-pg/README.md
> +
```suggestion

See also the Kubernetes documentation [Create a Secret](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#create-a-secret).

```

2024-04-25 20:53 UTC, stevepiercy commented on plone6-classic-pg/README.md
> +[Create the secret](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#create-a-secret) e.g. using `kubectl`:
```suggestion
Using the `kubectl` command, you can create a secret.
```

2024-04-25 20:53 UTC, stevepiercy commented on plone6-volto-pg-nginx-varnish/README.md
> +Database credentials (database name, user name, password) are expected in a secret.
Is host required as well, or is localhost assumed as default?

```suggestion
Database credentials (database name, user name, and password) are expected in a secret.
```

2024-04-25 20:53 UTC, stevepiercy commented on plone6-volto-pg-nginx-varnish/README.md
> +[Create the secret](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#create-a-secret) e.g. using `kubectl`:
```suggestion
Using the `kubectl` command, you can create a secret.
```

2024-04-25 20:53 UTC, stevepiercy commented on plone6-volto-pg-nginx-varnish/README.md
> +```
````suggestion
```

See also the Kubernetes documentation [Create a Secret](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#create-a-secret).

````

2024-04-25 20:53 UTC, stevepiercy commented on plone6-volto-pg/README.md
> +
```suggestion

See also the Kubernetes documentation [Create a Secret](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#create-a-secret).

```

2024-04-25 20:53 UTC, stevepiercy commented on plone6-volto-pg/README.md
> +[Create the secret](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#create-a-secret) e.g. using `kubectl`:
```suggestion
Using the `kubectl` command, you can create a secret.
```

2024-04-25 20:53 UTC, stevepiercy commented on plone6-volto-pg/README.md
> +Database credentials (database name, user name, password) are expected in a secret.
Is host required as well, or is localhost assumed as default?

```suggestion
Database credentials (database name, user name, and password) are expected in a secret.
```

2024-04-26 08:00 UTC, tschorr commented on plone6-classic-nodb/README.md
> +Database credentials (database name, user name, password) are expected in a secret.
PostgreSQL database cluster host and port are not configured with the secret. I have tried to elaborate on the database configuration in the README. Imo database cluster host and port should not be secret, they are not part of the credentials needed to access the actual database (you can move the database between database clusters without having to change the credentials). Maybe we need to this discuss this later, but let's start like this.

2024-04-26 09:09 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +You will need to access to the PostgreSQL database cluster for Plone, see the next section.
```suggestion
You will need access to the PostgreSQL database cluster for Plone.
See the next section.
```

2024-04-26 09:10 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +There is no sensible default for this option, you will have to modify it.
```suggestion
There is no sensible default for this option.
You will have to modify it.
```

2024-04-26 09:20 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +Database credentials (database name, user name, password) are expected in a secret.
I don't have an opinion. I wanted to make sure that the omission was deliberate, not an oversight, and that the host was defined somewhere. I don't know how to connect to a database without a host parameter.

Should the host configuration be applied to the other three README.mds?

2024-04-26 10:49 UTC, tschorr commented on plone6-classic-nodb/README.md
> +You will need to access to the PostgreSQL database cluster for Plone, see the next section.
argh there's a missing 'configure' in my sentence, it should be: 'You will need to configure access to the ...'. Does that have an impact on your suggestion?

2024-04-26 10:51 UTC, tschorr commented on plone6-classic-nodb/README.md
> +Database credentials (database name, user name, password) are expected in a secret.
> Should the host configuration be applied to the other three README.mds?

No, at least not in the same fashion. The other charts come with an included database, so there is no need to configure host + port.

2024-04-26 10:51 UTC, stevepiercy commented on plone6-classic-nodb/README.md
> +You will need to access to the PostgreSQL database cluster for Plone, see the next section.
Updated suggestion.

2024-04-26 18:28 UTC, stevepiercy approved these changes
Thank you!

2024-04-27 08:24 UTC, merged